name: dApp
description: A new dApp based on Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.3
  http: ^1.2.1
  flutter_secure_storage: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - src/artifacts/GeoCoordinates.json